### ISSUE TITLE
[I2C] How do you write 0 bytes?

### ISSUE THREAD

**Issue by AoiKagase** [FrankPfattheicher/IctBaden.RasPi#1]
I use CCS811 Sensor.
0 byte write is required at startup. is this possible?

[Datasheet]
https://cdn.sparkfun.com/assets/learn_tutorials/1/4/3/CCS811_Datasheet-DS000459.pdf
https://cdn.sparkfun.com/datasheets/BreakoutBoards/CCS811_Programming_Guide.pdf

**Comment by FrankPfattheicher** [comment]
Hi,
The mentioned i2c_write with zero bytes is defined as
void i2c_write(u8 address, u8 register, u8 *tx_data_ptr, u8 length);

This includes the register address (one byte).

So the following code should do it:
``` csharp
var i2c = new I2C();
i2c.Open(I2C.Device1, CCS_811_ADDRESS);
byte registerAddress = STATUS_REG;
i2c.Write(registerAddress);
```

**Comment by AoiKagase** [comment]
Nice, work!
Thank you very much!
